### ISSUE TITLE
[BUG] inotify watches out of control

### ISSUE THREAD

**Issue by hongkongkiwi** [saltydk/SARotate#10]
I don't understand why, but it looks like all the inotify watches are being used by SARotate.

I guess it's a bug in the code where the watches are not being released.

Here's a script to find the number of inotify watches:
[https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers)

```
   INOTIFY   INSTANCES
   WATCHES      PER
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
   53121         1      388308 root        /usr/local/bin/SARotate --config /etc/sarotate/config.yaml --logfile /var/log/sarotate/sarotate.log
```

I guess there's no reason why sarotate should use up 53121 inotify watches.

**Comment by saltydk** [comment]
```
   INOTIFY   INSTANCES
   WATCHES      PER
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
       2         2        8054 salty       /opt/sarotate/SARotate
```
Not sure what is happening with your instance.

**Comment by saltydk** [comment]
Building 2.0.7 now, please let us know if that helps.

**Comment by hongkongkiwi** [comment]
Thanks! Seems better now.
