### ISSUE TITLE
Most recently modified files don't show up on mount

### ISSUE THREAD

**Issue by atmos-o** [saltydk/SARotate#2]
I've noticed this only when using SArotate: when I make changes to my mounted remote it does not show me whatever change was made. And when I upload something new it's completely missing. Until I remount it. 

I normally don't have this issue with regularly mounting. My Service Accounts are setup properly as it correctly uploads & remounting using same SA shows proper files. 

This is my service file for my mount: 
```
[Unit]
Description=GDrive Mount Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
KillMode=none

ExecStart=/usr/bin/rclone mount gd: /data/arr/gd \
--config=/home/sv/.config/rclone/rclone.conf \
--allow-other \
--buffer-size=128M \
--use-mmap \
--poll-interval=5s \
--vfs-cache-mode=full \
--vfs-cache-max-age=6h \
--vfs-cache-max-size 0G \
--cache-dir=/data/sshd/rclone/cache \
--rc \
--rc-user=admin \
--rc-pass=WrL3uM67 \
--rc-addr=localhost:5572 \
--umask 002 \
--log-file=/data/rc/logs/mount-gd.log \
--log-level INFO \


ExecStop=/bin/fusermount -uz /data/arr/gd
Restart=on-failure
RestartSec=5
User=sv

[Install]
WantedBy=default.target
```

**Comment by saltydk** [comment]
This project doesn't really change how Rclone works in terms of polling. If you're having issues related to the service accounts then make sure all of them have the correct permissions.

**Comment by atmos-o** [comment]
I just checked now & all my SA's are added as owner to a group & that is added on my drive.

Can I get your or anyone else's working rclone mount with flags to see if it's a config issue or permission issue

**Comment by saltydk** [comment]
```
[Unit]
Description=Rclone VFS Mount
After=network-online.target

[Service]
User=salty
Group=salty
Type=notify
ExecStartPre=/bin/sleep 10
ExecStart=/usr/bin/rclone mount \
  --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36' \
  --config=/home/salty/.config/rclone/rclone.conf \
  --allow-other \
  --fast-list \
  --async-read=true \
  --dir-cache-time=5000h \
  --buffer-size=32M \
  --poll-interval=15s \
  --rc \
  --rc-no-auth \
  --rc-addr=localhost:5629 \
  --use-mmap \
  --vfs-read-ahead=128M \
  --vfs-read-chunk-size=32M \
  --vfs-read-chunk-size-limit=2G \
  --vfs-cache-max-age=504h \
  --vfs-cache-mode=full \
  --vfs-cache-poll-interval=30s \
  --vfs-cache-max-size=1T \
  --timeout=10m \
  --drive-skip-gdocs \
  --drive-pacer-min-sleep=10ms \
  --drive-pacer-burst=1000 \
  --umask=002 \
  --syslog \
  -v \
  union: /mnt/union
ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr localhost:5629 _async=true
ExecStop=/bin/fusermount -uz /mnt/union
Restart=on-abort
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=default.target
```
Not going to explain what each setting does though. So best of luck :)

**Comment by atmos-o** [comment]
yep no worries. I recognise most of em & might as well mess around and see whats best for me.

**Comment by atmos-o** [comment]
Issue persists after using your template (only thing is I couldn't run it when I included `ExecStartPost=/usr/bin/rclone rc vfs/refresh recursive=true --rc-addr localhost:5629 _async=true` so left it out)

The issue only happens when executing a script to `rclone move` it all over. Maybe the issue is there. What method do you use to sync it over? My script basically does `rclone move $LOCAL $REMOTE --log-file $LOGFILE -v --exclude-from $EXCLUDES --delete-empty-src-dirs`

**Comment by saltydk** [comment]
I use [crop](https://github.com/l3uddz/crop) but this is kind of outside of what I'm willing to support on this repo. Not sure this issue is related to anything the program does.
