### ISSUE TITLE
running sarotate on arm based system

### ISSUE THREAD

**Issue by poornachandratejasvi** [saltydk/SARotate#6]
i tried to run the sarotate om arm based system , and it was not able to run . will there be support for arm ? 

./SARotate : 
-bash: ./SARotate: cannot execute binary file: Exec format error

uname -m:
aarch64

cat /etc/os-release : 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by saltydk** [comment]
You need a binary built for that arch. Try the arm one in https://github.com/saltydk/SARotate/actions/runs/1554004613

**Comment by poornachandratejasvi** [comment]
> You need a binary built for that arch. Try the arm one in https://github.com/saltydk/SARotate/actions/runs/1554004613

im not able to find the url for the arm binary, can any one share

**Comment by saltydk** [comment]
New release should have them listed in releases.

**Comment by poornachandratejasvi** [comment]
> New release should have them listed in releases.

thanks , it works like a charm on arm64 too
